apiVersion: v1
kind: Service
metadata:
  name: meetwhen
  labels:
    app: meetwhen
spec:
  selector:
    app: meetwhen
  ports:
    - name: http        # ServiceMonitor / Ingress 가 이 이름을 참조
      port: 80
      targetPort: 8000
